import { useMemo, useState } from "react"
import { motion } from "framer-motion"
import Tex from "../../components/Tex"
import TopicShell, { Section, Card } from "../../components/TopicShell"
import { TOPICS } from "../../topics"

const topic = TOPICS.find((t) => t.slug === "as/groups")!

// A group with named elements and multiplication table
type Group = {
  id: string
  name: string
  tex: string
  elems: string[]
  // product index: mul[i][j] = index of elems[i] * elems[j]
  mul: number[][]
  order: number
  abelian: boolean
  cyclic: boolean
  generators?: number[]
  note?: string
}

// Z_n under addition
function buildZn(n: number): Group {
  const elems = Array.from({ length: n }, (_, i) => String(i))
  const mul = Array.from({ length: n }, (_, i) =>
    Array.from({ length: n }, (_, j) => (i + j) % n),
  )
  return {
    id: `Z${n}`,
    name: `ℤ/${n}ℤ`,
    tex: String.raw`\mathbb{Z}/${n}\mathbb{Z}`,
    elems,
    mul,
    order: n,
    abelian: true,
    cyclic: true,
    generators: [1],
    note: `Additive group of integers mod ${n}. Cyclic, generated by 1.`,
  }
}

// D_n dihedral group of order 2n — {r^0, r^1, ..., r^{n-1}, s, sr, sr^2, ..., sr^{n-1}}
// with r^n = e, s^2 = e, srs = r^{-1}
function buildDn(n: number): Group {
  const size = 2 * n
  const label = (i: number): string => {
    if (i < n) {
      if (i === 0) return "e"
      if (i === 1) return "r"
      return `r${i}`
    }
    const k = i - n
    if (k === 0) return "s"
    if (k === 1) return "sr"
    return `sr${k}`
  }
  const elems = Array.from({ length: size }, (_, i) => label(i))
  // encode element as (sign, k) where sign ∈ {0,1} and k ∈ {0..n-1}
  // i < n: (0, i);  i >= n: (1, i - n)
  const decode = (i: number): [number, number] =>
    i < n ? [0, i] : [1, i - n]
  const encode = (s: number, k: number): number =>
    (k + n) % n + (s === 1 ? n : 0)
  const mul = Array.from({ length: size }, (_, i) =>
    Array.from({ length: size }, (_, j) => {
      const [s1, k1] = decode(i)
      const [s2, k2] = decode(j)
      // (s1, k1)(s2, k2) = ?
      // if s1=0: (0,k1)(s2,k2) = (s2, k1 + k2)
      // if s1=1: (1,k1)(0,k2) = (1, k1 - k2)
      // if s1=1,s2=1: (1,k1)(1,k2) = (0, k1 - k2)
      if (s1 === 0) return encode(s2, k1 + k2)
      if (s2 === 0) return encode(1, k1 - k2)
      return encode(0, k1 - k2)
    }),
  )
  return {
    id: `D${n}`,
    name: `D${n}`,
    tex: String.raw`D_{${n}}`,
    elems,
    mul,
    order: 2 * n,
    abelian: n <= 2,
    cyclic: false,
    generators: [1, n],
    note: `Dihedral group — symmetries of a regular ${n}-gon (n rotations + n reflections).`,
  }
}

// S_3 symmetric group
function buildS3(): Group {
  // Elements: e, (12), (13), (23), (123), (132)
  type Perm = [number, number, number] // image of 1,2,3
  const perms: Perm[] = [
    [1, 2, 3], // e
    [2, 1, 3], // (12)
    [3, 2, 1], // (13)
    [1, 3, 2], // (23)
    [2, 3, 1], // (123): 1→2, 2→3, 3→1
    [3, 1, 2], // (132): 1→3, 2→1, 3→2
  ]
  const labels = ["e", "(12)", "(13)", "(23)", "(123)", "(132)"]
  const compose = (a: Perm, b: Perm): Perm => [b[a[0] - 1], b[a[1] - 1], b[a[2] - 1]]
  const match = (p: Perm) =>
    perms.findIndex((q) => q[0] === p[0] && q[1] === p[1] && q[2] === p[2])
  const mul = perms.map((a) => perms.map((b) => match(compose(a, b))))
  return {
    id: "S3",
    name: "S₃",
    tex: String.raw`S_3`,
    elems: labels,
    mul,
    order: 6,
    abelian: false,
    cyclic: false,
    note: "Symmetric group on 3 letters — smallest non-abelian group.",
  }
}

// Klein four-group
function buildV4(): Group {
  const elems = ["e", "a", "b", "ab"]
  // a^2 = b^2 = e, ab = ba
  // indexing: e=0, a=1, b=2, ab=3
  const mul = [
    [0, 1, 2, 3],
    [1, 0, 3, 2],
    [2, 3, 0, 1],
    [3, 2, 1, 0],
  ]
  return {
    id: "V4",
    name: "V₄",
    tex: String.raw`V_4 = \mathbb{Z}_2 \times \mathbb{Z}_2`,
    elems,
    mul,
    order: 4,
    abelian: true,
    cyclic: false,
    note: "Klein four-group. Every non-identity element has order 2.",
  }
}

const GROUPS: Group[] = [buildZn(4), buildZn(6), buildV4(), buildDn(3), buildDn(4), buildS3()]

// order of an element: smallest k with g^k = e
function elementOrder(G: Group, g: number): number {
  let cur = g
  for (let k = 1; k <= G.order; k++) {
    if (cur === 0) return k
    cur = G.mul[cur][g]
  }
  return -1
}

// subgroup generated by a single element
function cyclicSubgroup(G: Group, g: number): number[] {
  const out = new Set<number>([0])
  let cur = g
  while (!out.has(cur)) {
    out.add(cur)
    cur = G.mul[cur][g]
  }
  return Array.from(out).sort((a, b) => a - b)
}

function CayleyTable() {
  const [id, setId] = useState("Z6")
  const G = GROUPS.find((g) => g.id === id)!
  const [sel, setSel] = useState<{ i: number; j: number } | null>(null)

  const rowColors = useMemo(() => {
    // color each cell based on its value — hash to hue
    return (v: number) => {
      const hue = (v * 360) / G.order
      return `hsl(${hue} 60% 45%)`
    }
  }, [G.order])

  const cellSize = Math.max(28, Math.min(46, 360 / G.order))

  const elemOrders = G.elems.map((_, i) => elementOrder(G, i))

  return (
    <Card>
      <p className="text-sm text-neutral-400 mb-3">
        <strong className="text-neutral-200">Cayley table.</strong> Each cell{" "}
        <Tex math={String.raw`(i, j)`} /> holds the product{" "}
        <Tex math={String.raw`g_i \cdot g_j`} />. Click any cell to highlight the
        equation.
      </p>

      <div className="flex flex-wrap items-center gap-2 mb-3">
        {GROUPS.map((g) => (
          <button
            key={g.id}
            onClick={() => {
              setId(g.id)
              setSel(null)
            }}
            className={`rounded-md border px-3 py-1 text-xs font-mono ${
              id === g.id
                ? "border-amber-500/60 bg-amber-500/20 text-amber-200"
                : "border-neutral-800 text-neutral-400 hover:bg-neutral-900"
            }`}
          >
            {g.name}
          </button>
        ))}
      </div>

      <div className="rounded-md border border-neutral-800 bg-neutral-950 p-3 overflow-x-auto">
        <table className="text-xs font-mono border-separate" style={{ borderSpacing: 2 }}>
          <thead>
            <tr>
              <td style={{ width: cellSize, height: cellSize }} className="text-center text-neutral-500">
                ·
              </td>
              {G.elems.map((e, j) => (
                <td
                  key={j}
                  style={{ width: cellSize, height: cellSize }}
                  className={`text-center rounded ${sel?.j === j ? "bg-amber-500/20 text-amber-200" : "text-neutral-400"}`}
                >
                  {e}
                </td>
              ))}
            </tr>
          </thead>
          <tbody>
            {G.elems.map((ei, i) => (
              <tr key={i}>
                <td
                  style={{ width: cellSize, height: cellSize }}
                  className={`text-center rounded ${sel?.i === i ? "bg-amber-500/20 text-amber-200" : "text-neutral-400"}`}
                >
                  {ei}
                </td>
                {G.elems.map((_ej, j) => {
                  const val = G.mul[i][j]
                  const isSelCell = sel?.i === i && sel?.j === j
                  const inSelRow = sel?.i === i
                  const inSelCol = sel?.j === j
                  return (
                    <td
                      key={j}
                      onClick={() => setSel({ i, j })}
                      style={{
                        width: cellSize,
                        height: cellSize,
                        backgroundColor: rowColors(val),
                      }}
                      className={`text-center text-white rounded cursor-pointer transition-all ${
                        isSelCell ? "ring-2 ring-amber-300" : inSelRow || inSelCol ? "ring-1 ring-amber-400/40" : ""
                      }`}
                    >
                      {G.elems[val]}
                    </td>
                  )
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {sel && (
        <div className="mt-3 rounded-md border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-amber-200 text-sm">
          <Tex math={`${G.elems[sel.i]} \\cdot ${G.elems[sel.j]} = ${G.elems[G.mul[sel.i][sel.j]]}`} />
        </div>
      )}

      <div className="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-mono">
        <div className="rounded-md border border-neutral-800 bg-neutral-900 px-3 py-2">
          <div className="text-[10px] uppercase tracking-wider text-neutral-500">order</div>
          <div className="mt-0.5 text-neutral-200">{G.order}</div>
        </div>
        <div className={`rounded-md border px-3 py-2 ${G.abelian ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-200" : "border-rose-500/40 bg-rose-500/10 text-rose-200"}`}>
          <div className="text-[10px] uppercase tracking-wider opacity-70">abelian?</div>
          <div className="mt-0.5">{G.abelian ? "yes" : "no"}</div>
        </div>
        <div className={`rounded-md border px-3 py-2 ${G.cyclic ? "border-indigo-500/40 bg-indigo-500/10 text-indigo-200" : "border-neutral-800 bg-neutral-900 text-neutral-400"}`}>
          <div className="text-[10px] uppercase tracking-wider opacity-70">cyclic?</div>
          <div className="mt-0.5">{G.cyclic ? "yes" : "no"}</div>
        </div>
        <div className="rounded-md border border-neutral-800 bg-neutral-900 px-3 py-2">
          <div className="text-[10px] uppercase tracking-wider text-neutral-500">identity</div>
          <div className="mt-0.5 text-neutral-200">{G.elems[0]}</div>
        </div>
      </div>

      <div className="mt-3 rounded-md border border-neutral-800 bg-neutral-950 p-3">
        <div className="text-xs text-neutral-500 mb-2">element orders</div>
        <div className="grid grid-cols-6 sm:grid-cols-12 gap-1 text-xs font-mono">
          {G.elems.map((e, i) => (
            <div key={i} className="rounded border border-neutral-800 px-1 py-1 text-center">
              <div className="text-neutral-300">{e}</div>
              <div className="text-[10px] text-amber-300">ord {elemOrders[i]}</div>
            </div>
          ))}
        </div>
      </div>

      {G.note && <p className="mt-3 text-xs text-neutral-500">{G.note}</p>}
    </Card>
  )
}

function SubgroupExplorer() {
  const [id, setId] = useState("D3")
  const G = GROUPS.find((g) => g.id === id)!
  const [g, setG] = useState(1)

  const subgroup = useMemo(() => cyclicSubgroup(G, g), [G, g])

  return (
    <Card>
      <p className="text-sm text-neutral-400 mb-3">
        <strong className="text-neutral-200">Cyclic subgroups.</strong>{" "}
        <Tex math={String.raw`\langle g \rangle = \{e, g, g^2, \ldots \}`} /> has
        order equal to the order of g, which divides <Tex math="|G|" /> (Lagrange).
      </p>

      <div className="flex flex-wrap items-center gap-2 mb-3">
        {GROUPS.map((gr) => (
          <button
            key={gr.id}
            onClick={() => {
              setId(gr.id)
              setG(1)
            }}
            className={`rounded-md border px-3 py-1 text-xs font-mono ${
              id === gr.id
                ? "border-amber-500/60 bg-amber-500/20 text-amber-200"
                : "border-neutral-800 text-neutral-400 hover:bg-neutral-900"
            }`}
          >
            {gr.name}
          </button>
        ))}
      </div>

      <div className="flex flex-wrap items-center gap-2 mb-3">
        {G.elems.map((e, i) => (
          <button
            key={i}
            onClick={() => setG(i)}
            className={`rounded-md border px-3 py-1 text-xs font-mono ${
              g === i ? "border-indigo-500/60 bg-indigo-500/20 text-indigo-200" : "border-neutral-800 text-neutral-400 hover:bg-neutral-900"
            }`}
          >
            {e}
          </button>
        ))}
      </div>

      <div className="rounded-md border border-neutral-800 bg-neutral-950 p-4">
        <div className="text-sm">
          <span className="text-neutral-400">⟨{G.elems[g]}⟩ = </span>
          <span className="font-mono text-emerald-300">
            {"{ "}
            {subgroup.map((i, k) => (
              <span key={i}>
                {k > 0 && ", "}
                {G.elems[i]}
              </span>
            ))}
            {" }"}
          </span>
        </div>
        <div className="mt-2 text-xs text-neutral-500 font-mono">
          |⟨{G.elems[g]}⟩| = <span className="text-amber-300">{subgroup.length}</span>
          {" "}divides |G| = {G.order}{" "}
          <span className={subgroup.length > 0 && G.order % subgroup.length === 0 ? "text-emerald-300" : "text-rose-300"}>
            ✓ Lagrange
          </span>
        </div>
      </div>

      <div className="mt-4 grid gap-1 text-xs font-mono">
        <div className="text-neutral-500">powers of {G.elems[g]}:</div>
        <div className="flex flex-wrap gap-1">
          {subgroup.map((i, k) => {
            let cur = 0
            for (let m = 0; m < k; m++) cur = G.mul[cur][g]
            void cur
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, scale: 0.5 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: k * 0.04 }}
                className="rounded border border-indigo-500/40 bg-indigo-500/10 text-indigo-200 px-2 py-0.5"
              >
                {G.elems[g]}^{k} = {G.elems[i]}
              </motion.div>
            )
          })}
        </div>
      </div>
    </Card>
  )
}

function GroupAxioms() {
  return (
    <Card>
      <div className="grid gap-3 md:grid-cols-2">
        {[
          {
            name: "Closure",
            tex: String.raw`\forall a, b \in G,\ a \cdot b \in G`,
          },
          {
            name: "Associativity",
            tex: String.raw`\forall a, b, c \in G,\ (a \cdot b) \cdot c = a \cdot (b \cdot c)`,
          },
          {
            name: "Identity",
            tex: String.raw`\exists e \in G:\ \forall a,\ e \cdot a = a \cdot e = a`,
          },
          {
            name: "Inverses",
            tex: String.raw`\forall a \in G,\ \exists a^{-1}:\ a \cdot a^{-1} = a^{-1} \cdot a = e`,
          },
        ].map((d) => (
          <div key={d.name} className="rounded-md border border-neutral-800 bg-neutral-950 p-3">
            <div className="text-xs uppercase tracking-wider text-amber-300">{d.name}</div>
            <div className="mt-2 overflow-x-auto">
              <Tex block math={d.tex} />
            </div>
          </div>
        ))}
      </div>
      <p className="mt-3 text-xs text-neutral-500">
        A set with one binary operation that satisfies all four is a{" "}
        <em>group</em>. Abelian adds commutativity{" "}
        <Tex math={String.raw`a \cdot b = b \cdot a`} />.
      </p>
    </Card>
  )
}

export default function Groups() {
  return (
    <TopicShell topic={topic}>
      <Section title="What is a group?">
        <GroupAxioms />
      </Section>
      <Section title="Cayley tables — click cells">
        <CayleyTable />
      </Section>
      <Section title="Cyclic subgroups and Lagrange">
        <SubgroupExplorer />
      </Section>
    </TopicShell>
  )
}
